//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGalaxyAPI")]
    public interface IGalaxyAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalaxyAPI/RunJob", ReplyAction="http://tempuri.org/IGalaxyAPI/RunJobResponse")]
        string RunJob(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalaxyAPI/RunJob", ReplyAction="http://tempuri.org/IGalaxyAPI/RunJobResponse")]
        System.Threading.Tasks.Task<string> RunJobAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalaxyAPI/Login", ReplyAction="http://tempuri.org/IGalaxyAPI/LoginResponse")]
        string Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalaxyAPI/Login", ReplyAction="http://tempuri.org/IGalaxyAPI/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGalaxyAPIChannel : WebApplication1.ServiceReference1.IGalaxyAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GalaxyAPIClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IGalaxyAPI>, WebApplication1.ServiceReference1.IGalaxyAPI {
        
        public GalaxyAPIClient() {
        }
        
        public GalaxyAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GalaxyAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GalaxyAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GalaxyAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RunJob(string data) {
            return base.Channel.RunJob(data);
        }
        
        public System.Threading.Tasks.Task<string> RunJobAsync(string data) {
            return base.Channel.RunJobAsync(data);
        }
        
        public string Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string login, string password) {
            return base.Channel.LoginAsync(login, password);
        }
    }
}
